### ISSUE TITLE
Duplicate project_id in update/nfs-shares events causing processing issues

### ISSUE THREAD

**Issue by notque** [sapcc/castellum#276]
I've identified an issue with the update/nfs-shares events being sent from Castellum. Specifically, the target.project_id field is sometimes being sent as an array containing duplicate project_id values, instead of a single string. This inconsistency is causing problems in our system, which expects target.project_id to be a single string value.

**Issue Details:**

In some events, the `target.project_id` field appears as follows:

```json
"project_id": [
  "6aecfb7bb0084f70b7fbe3b08bb7e0b5",
  "6aecfb7bb0084f70b7fbe3b08bb7e0b5"
]
```

This causes our system to interpret target.project_id as an array rather than a string, leading to errors during event processing.

Hermes is designed to accept a single string value for target.project_id. The unexpected array with duplicate entries is causing parsing errors and disrupting our data once in Opensearch. I can implement a workaround in the Logstash step to handle this anomaly, but it would be more efficient and reliable if Castellum could address the root cause.

**Comment by majewsky** [comment]
I have trouble imagining how this can happen, given that we always use `type cadf.Resource` for targets, which defines the ProjectID field as `string`.

Can you link me to one of these audit events via DM? Maybe looking at the concrete event might shed light on how we got there.

**Comment by notque** [comment]
Closing for now, we have other solutions, and can follow up if required. Thank you for your consideration.
